### ISSUE TITLE
Media Queries 

### ISSUE THREAD

**Issue by MaddPaige** [MaddPaige/GrandmaMcgarvey#2]
Hey I have been trying to use media queries to make my website adaptable to different screen sizes however it doesn't seem to be working probably I have done the size for width 400 and 700 but when i did for 1000 it doesn't seem to be changing and then when i make changes it changes the layout for the 400 design width as well. Not sure what i am doing wrong.
![Screen Shot 2019-10-03 at 12 12 40 PM](https://user-images.githubusercontent.com/43526594/66088324-31569d00-e5d7-11e9-841f-84f308448afc.png)
![Screen Shot 2019-10-03 at 12 12 51 PM](https://user-images.githubusercontent.com/43526594/66088325-31ef3380-e5d7-11e9-9b26-c52bea0b3067.png)
![Screen Shot 2019-10-03 at 12 13 01 PM](https://user-images.githubusercontent.com/43526594/66088326-31ef3380-e5d7-11e9-9648-289a076ec88e.png)

**Comment by sehsarah** [comment]
Can you add @ellysmlly to this repo @MaddPaige ?

**Comment by MaddPaige** [comment]
Hi @sehsarah, I have sent elly a collaborator request but she hasn't accepted so I can't add her to the repo .

**Comment by ellysmlly** [comment]
Sweet. I've looked into this and its a great issue! Something we can discuss more in class too 👍 

Our CSS file is read from the top to bottom and so when we define a class at the top of our file and then again lower down in the file, the lower styling will override what was written above. 

**To explain using an example from your CSS –** 

You have defined styling changes when your screen size is smaller than 400px –
https://github.com/MaddPaige/Grandma-Mcgarvey-/blob/a25319a7350a74147c42a56c58f379a9dbda3c1d/styles/style.css#L160

Then after that you have defined styling changes when your screen size is smaller than 700px –
https://github.com/MaddPaige/Grandma-Mcgarvey-/blob/a25319a7350a74147c42a56c58f379a9dbda3c1d/styles/style.css#L277

And then after that you have defined what happens when your screen size is smaller than 1000px –
https://github.com/MaddPaige/Grandma-Mcgarvey-/blob/a25319a7350a74147c42a56c58f379a9dbda3c1d/styles/style.css#L390

So all the styles for a screen size smaller than 1000px are overriding both the 400px media query & the 700px media query

As you can see in this screenshot - the 400px & 700px styles are crossed out, because the 1000px media query is overriding those styles
<img width="234" alt="Screen Shot 2019-10-15 at 12 03 08 am" src="https://user-images.githubusercontent.com/13416564/66746791-4ab4ee80-eedf-11e9-8a77-0cd3fa1c04f1.png">

Media queries are basically used to tell the browser –
When my screen size is smaller than 700px override `gm-BANANA4-container` with this new style

**So the solution –** 
You want to change the order of your media queries so that when you read your CSS file from top to bottom it follows the order of styles you want to override the next 

eg.
when my screen size is smaller than 1000px change ABC
then 
when my screen size is smaller than 700px change ABC
then
when my screen size is smaller than 400px change ABC

Does this make sense? Comment back any questions 

I can go over this again for everyone during class on Thursday too

👍

**Comment by MaddPaige** [comment]
Hi elly,

Thank you This makes sense I will give it a go today. Sorry I’m not going to make it into class today as I’m not feeling great. Will be there on Thursday though!

Thank you

Maddi
________________________________

**Comment by sehsarah** [comment]
Has this been fixed now @MaddPaige ? You can close this then
